package-lock.json, package.json, src/cjs.js, src/index.js, src/minify.js, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap, test/cjs.test.js, test/fixtures/simple.html, test/fixtures/simple.js, test/helpers/getCompiler.js, test/helpers/readAssets.js
Minify html with `html-minifier-terser`
No
No
=> Feat: minify html

src/options.json, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap, test/__snapshots__/htmlMinimizerOptions-option.test.js.snap, test/__snapshots__/validate-options.test.js.snap, test/htmlMinimizerOptions-option.test.js, test/validate-options.test.js
=> test: options

test/__snapshots__/exclude-option.test.js.snap.webpack4, test/__snapshots__/exclude-option.test.js.snap.webpack5, test/__snapshots__/include-option.test.js.snap.webpack4, test/__snapshots__/include-option.test.js.snap.webpack5, test/exclude-option.test.js, test/fixtures/include-exclude/exclude-1.html, test/fixtures/include-exclude/exclude-2.html, test/fixtures/include-exclude/include-1.html, test/fixtures/include-exclude/include-2.html, test/fixtures/include-exclude/include-3.html, test/fixtures/include-exclude/include-4.html, test/include-option.test.js
Added tests for `include`, `exclude` options
No
No
=> Test: include exclude options

src/options.json, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap.webpack4, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap.webpack5, test/__snapshots__/validate-options.test.js.snap.webpack4, test/__snapshots__/validate-options.test.js.snap.webpack5, test/helpers/emitAssetInChildCompilationLoader.js, test/validate-options.test.js
Added tests.
Increased code coverage
No
No
=> Test: increased code coverage

src/index.js, src/minify.js, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap.webpack4, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap.webpack5, test/fixtures/broken-html-syntax.html
Refactor errors processing
No
No
=> Refactor: errors processing

README.md
Added docs, how to use the plugin
No
No
=> docs: plugin usage

test/__snapshots__/minify-option.test.js.snap.webpack4, test/__snapshots__/minify-option.test.js.snap.webpack5, test/minify-option.test.js
Added tests for `minify` option
No
No
=> Test: minify option

test/__snapshots__/test-option.test.js.snap.webpack4, test/__snapshots__/test-option.test.js.snap.webpack5, test/test-option.test.js
Added tests for `test` option
No
No
=> Test: test option

README.md, package-lock.json, package.json
=> chore: updated metadata

package-lock.json, package.json
Removed url-loader from devDependencies
No
No
=> chore: removed url-loader from devDependencies

README.md
=> Docs: updated

.github/workflows/nodejs.yml
Changed webpack versions
No
No
=> ci: updated

package-lock.json, package.json, src/index.js, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap, test/helpers/EmitNewAsset.js, test/helpers/getCompiler.js, test/helpers/index.js
Run optimize against assets added later by plugins
No
No
=> Feat: run optimize against assets added later by plugins

README.md
Removed `file-loader` in favor `asset modules`
No
No
=> docs: removed `file-loader` in favor `asset modules`

package-lock.json, package.json, test/helpers/getCompiler.js
Removed `file-loader` in favor `asset modules`
No
No
=> test: update

.github/workflows/nodejs.yml, .husky/commit-msg, .husky/pre-commit, babel.config.js, package-lock.json, package.json, src/index.js, test/worker.test.js
Support `Node.js` v10 dropped
Support `Node.js` v10 dropped
No
=> refactor: Node.js v10 dropped

package-lock.json, package.json, src/index.js, test/parallel-option.test.js
`jest-worker` package updated
`jest-worker` package updated
No
=> refactor: jest-worker updated

README.md, src/index.js, src/minify.js, src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/minify-option.test.js
`minify` opton returns an object with keys `code`, `warnings`, `errors`
No
No
=> refactor: minify option

.github/workflows/nodejs.yml
=> chore: update commitlint github action to v4

README.md, package-lock.json, src/index.js, test/HtmlMinimizerPlugin.test.js, test/__snapshots__/HtmlMinimizerPlugin.test.js.snap, test/__snapshots__/minify-option.test.js.snap, test/minify-option.test.js
better formatting error/warning messages
No
No
=> fix: warnings and errors text messages

.github/workflows/nodejs.yml
=> ci: added nodejs v17

package-lock.json, package.json, src/index.js, src/minify.js, src/utils.js, test/__snapshots__/worker.test.js.snap, test/worker.test.js, tsconfig.json, types/cjs.d.ts, types/index.d.ts, types/minify.d.ts, types/utils.d.ts
=> feat: added types and refactor

README.md
Adds proper type definitions in readme
=> docs(readme): added type definitions

package-lock.json
=> fix: security issue

.github/workflows/nodejs.yml, babel.config.js, package-lock.json, package.json
=> refactor!: minimum supported `Node.js` version is `14.15.0`

package-lock.json, package.json
https://github.com/terser/html-minifier-terser/releases/tag/v7.0.0
No
No
=> feat: update `html-minifier-terser` to v7

README.md, package-lock.json, package.json, src/index.js, src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/minify-option.test.js, types/index.d.ts, types/utils.d.ts
Add SWC HTML minifier
No
Some bugs on `@swc/html` side, so let's wait fixing them:
- Wrong `main`
- No `types`
=> feat: added SWC HTML minifier

package-lock.json, package.json
fix crash due bug in `jest-worker`
No
No
=> fix: crash

README.md, package-lock.json, package.json, src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/helpers/getCompiler.js, test/minify-option.test.js
Fix compatibility with swc
No
No
=> fix: compatibility with swc

README.md, src/index.js, src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/fixtures/template.html, test/minify-option.test.js, types/index.d.ts, types/utils.d.ts
Allow to minify HTML fragments
No
No
=> Feat swc minify fragment

package-lock.json, package.json, src/utils.js
Refactor code + fix types
No
No
=> refactor: code and types

.github/workflows/dependency-review.yml, package-lock.json
=> chore: fix npm audit 

package-lock.json, package.json, types/index.d.ts
=> chore: update typescript

README.md
=> docs: fix incorrect hyperlink

.github/workflows/nodejs.yml, tsconfig.json
=> chore: fix commitlint check

.github/workflows/nodejs.yml, .husky/commit-msg, .husky/pre-commit, package-lock.json, package.json, test/__snapshots__/minify-option.test.js.snap, test/minify-option.test.js
=> chore: deps update

src/index.js, src/minify.js, types/index.d.ts
=> refactor: code

package-lock.json, package.json
update jest from v29 to v30
No
No
=> chore: update jest from v29 to v30
